### ISSUE TITLE
[AVM Module Issue]: Fails when no terraform changes and no identity defined

### ISSUE THREAD

**Issue by christerengman** [Azure/terraform-azurerm-avm-res-cache-redis#54]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.1.5

### Description

Minimal terraform config (for me tag configuration was required to achieve desired state as we have implemented tag inheritance using policies, but I guess you could skip that if that's not the case):
```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3"
    }
  }
}

provider "azurerm" {
  features {}
}

locals {
  location = "swedencentral"
}

data "azurerm_subscription" "current" {}

module "naming" {
  source  = "Azure/naming/azurerm"
  version = "~> 0.4"
}

resource "azurerm_resource_group" "main" {
  location = local.location
  name     = module.naming.resource_group.name_unique

  tags = data.azurerm_subscription.current.tags
}

module "redis" {
  source  = "Azure/avm-res-cache-redis/azurerm"
  version = "~> 0.1"

  location            = azurerm_resource_group.main.location
  name                = module.naming.redis_cache.name_unique
  resource_group_name = azurerm_resource_group.main.name

  capacity         = 0
  enable_telemetry = false
  sku_name         = "Basic"
  tags             = azurerm_resource_group.main.tags
  zones            = null
}
```
`terraform apply`, first run:
Success

`terraform applyplResult, second run:
╷
│ Error: Unsupported attribute
│
│   on .terraform\modules\redis\outputs.tf line 25, in output "system_assigned_mi_principal_id":
│   25:   value       = jsondecode(data.azapi_resource.this.output).identity.principalId
│     ├────────────────
│     │ data.azapi_resource.this.output is "{\"id\":\"/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/rg-g6lz/providers/Microsoft.Cache/Redis/redis-xxxx\",\"location\":\"Sweden Central\",\"name\":\"redis-xxxx\",\"properties\":{\"accessKeys\":null,\"enableNonSslPort\":false,\"hostName\":\"redis-g6lz.redis.cache.windows.net\",\"instances\":[{\"isMaster\":true,\"isPrimary\":true,\"sslPort\":15000}],\"linkedServers\":[],\"minimumTlsVersion\":\"1.2\",\"port\":6379,\"provisioningState\":\"Succeeded\",\"publicNetworkAccess\":\"Enabled\",\"redisConfiguration\":{\"maxclients\":\"256\",\"maxfragmentationmemory-reserved\":\"30\",\"maxmemory-delta\":\"30\",\"maxmemory-policy\":\"volatile-lru\",\"maxmemory-reserved\":\"30\",\"preferred-data-persistence-auth-method\":\"SAS\"},\"redisVersion\":\"6.0\",\"sku\":{\"capacity\":0,\"family\":\"C\",\"name\":\"Basic\"},\"sslPort\":6380,\"updateChannel\":\"Stable\"},\"tags\":{\"myTag\":\"myValue\"},\"type\":\"Microsoft.Cache/Redis\"}"
│
│ This object does not have an attribute named "identity".
╵

I guess `output.tf` should not expect identity to be configured as it's optional.

**Comment by jchancellor-ms** [comment]
@christerengman  - thanks for submitting this. I will look to address this as part of a v4 support release this week.  Thanks for submitting this issue.
