### ISSUE TITLE
[AVM Module Issue]:  Output system_assigned_mi_principal_id is incorrect

### ISSUE THREAD

**Issue by srg1177** [Azure/terraform-azurerm-avm-res-cache-redis#56]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.1.5

### Description

Output `system_assigned_mi_principal_id is incorrect` is declared incorrectly.

```
output "system_assigned_mi_principal_id" {
  description = "The resource id for the system managed identity principal id."
  value       = jsondecode(data.azapi_resource.this.output).identity.principalId
}
```

**this resource doesn't contain any attribute named** `principalId`

terraform plan - output 

```
│   on .terraform/modules/redis.redis/outputs.tf line 25, in output "system_assigned_mi_principal_id":
│   25:   value       = jsondecode(data.azapi_resource.this.output).identity.principalId
│     ├────────────────
│     │ data.azapi_resource.this.output is ".........

:\"Microsoft.Cache/Redis\"}"
│ 
│ This object does not have an attribute named "principalId".

```

Most probably must  be **principal_id** - [docs](https://registry.terraform.io/providers/Azure/azapi/latest/docs/data-sources/resource#principal_id-3) 

```
output "system_assigned_mi_principal_id" {
  description = "The resource id for the system managed identity principal id."
  value       = jsondecode(data.azapi_resource.this.output).identity.principal_id
}
```

**Comment by srg1177** [comment]
Ok no that I sorted the full output I see `principalId` is actually there but output cannot fetch it out..

data.azapi_resource.this.output is "{\"id\":\"/subscriptions//resourceGroups//providers/Microsoft.Cache/Redis/\",\"identity\":{\"type\":\"UserAssigned\",\"userAssignedIdentities\":{\"/subscriptions///providers/Microsoft.ManagedIdentity/userAssignedIdentities/\":{\"clientId\":\"\",\"principalId\":\"":\"Microsoft.Cache/Redis\"}"

**Comment by jchancellor-ms** [comment]
@srg1177 - thanks for reporting this bug.  Let me add this to the features for the next release supporting AzureRM 4.0 and azapi 2.0
