### ISSUE TITLE
[AVM Module Issue]: Documentation indicates support for Azure Cache for Redis Enterprise but throws an error when used

### ISSUE THREAD

**Issue by yrachakonda** [Azure/terraform-azurerm-avm-res-cache-redis#57]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.1.5

### Description

I created a module in my code to use Redis Cache AVM

module "redis_cache" {
  source  = "Azure/avm-res-cache-redis/azurerm"
  version = "0.1.5"

  other variables here...

}

This causes an error when tf apply is called 

╷
│ Error: expected sku_name to be one of ["Basic" "Standard" "Premium"], got Enterprise
│ 
│   with module.redis_cache_cluster.module.redis_cache.azurerm_redis_cache.this,
│   on .terraform/modules/redis_cache_cluster.redis_cache/main.rediscache.tf line 10, in resource "azurerm_redis_cache" "this":
│   10:   sku_name                      = var.sku_name
│ 
╵

I have looked through the azurerm documentation and the code for this AVM. There is no indication that this module only supports azurerm_redis_cache

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/redis_cache

It does not support creating a azurerm_redis_enterprise_cluster resource and a azurerm_redis_enterprise_database to support the cluster

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/redis_enterprise_cluster
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/redis_enterprise_database

Please update the documentation according to reflect what the AVM supports.

**Comment by jchancellor-ms** [comment]
@yrachakonda - Thanks for the feedback.  I will update the documentation to reflect the correct support items.  Also, can you confirm whether you require Enterprise support? If so, I can add it to the backlog for support in a future release.
